version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "actions/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: actions/notify-slack-publish-status
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
