name: "Setup"
description: "Do necessary setup for NX, node, pnpm cache and deps install"

runs:
  using: "composite"
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@e2e6dc8bce4b0387a05eb687735c39c41580b792

    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

    - name: Use Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
      with:
        node-version-file: ".nvmrc"
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"

    - name: Clear yarn cache (workaround for git-hosted packages)
      shell: bash
      run: yarn cache clean || true

    - name: install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
