title = "Unified SDK gitleaks config"

[whitelist]
# As of v4, gitleaks only matches against filename, not path in the
# files directive.  Leaving content for backwards compatibility.
files = [
  "(.*?)(jpg|gif|doc|pdf|bin)$",
  ".gitleaks.toml",
  "^.+\\.(t|j)sx?$"
]
