npm:
  publish: true
  publishPath: "sdk"
hooks:
  after:release:
    - 'echo Successfully released ${name} v${version} to ${repo.repository}.'
plugins:
  '@release-it-plugins/workspaces':
    workspaces: ['sdk']
  './.github/scripts/keep-a-changelog.mjs':
    filename: 'CHANGELOG.md'
    addUnreleased: true
    strictLatest: false	
