packages:
  - "sdk"
  - "packages/auth"
  - "packages/auth-next-server"
  - "packages/auth-next-client"
  - "packages/wallet"
  - "packages/config"
  - "packages/passport/sdk"
  - "packages/passport/sample-app"
  - "packages/orderbook"
  - "packages/internal/metrics"
  - "packages/internal/toolkit"
  - "packages/internal/cryptofiat"
  - "packages/internal/dex/sdk"
  - "packages/internal/bridge/sdk"
  - "packages/internal/generated-clients"
  - "packages/checkout/sdk"
  - "packages/checkout/sample-app"
  - "packages/checkout/widgets-lib"
  - "packages/blockchain-data/sdk"
  - "packages/audience/core"
  - "packages/audience/pixel"
  - "packages/audience/sdk"
  - "packages/audience/sample-app"
  - "packages/game-bridge"
  - "packages/webhook/sdk"
  - "packages/minting-backend/sdk"
  - "tests/**"

  # Setup catalog file versions for core packages like typescript/eslint
