packages:
  - "sdk"
  - "packages/config"
  - "packages/x-client"
  - "packages/x-provider"
  - "packages/x-provider/src/sample-app"
  - "packages/passport/sdk"
  - "packages/passport/sdk-sample-app"
  - "packages/orderbook"
  - "packages/internal/metrics"
  - "packages/internal/toolkit"
  - "packages/internal/cryptofiat"
  - "packages/internal/dex/sdk"
  - "packages/internal/dex/sdk-sample-app"
  - "packages/internal/bridge/sdk"
  - "packages/internal/generated-clients"
  - "packages/internal/bridge/bridge-sample-app"
  - "packages/checkout/sdk"
  - "packages/checkout/sdk-sample-app"
  - "packages/checkout/widgets-sample-app"
  - "packages/checkout/widgets-lib"
  - "packages/blockchain-data/sdk"
  - "packages/game-bridge"
  - "packages/webhook/sdk"
  - "packages/minting-backend/sdk"
  - "tests/**"
  - "examples/passport/**"
  - "examples/orderbook/**"
  - "examples/checkout/**"
  - "examples/blockchain-data"
  - "examples/contracts/**"
  - "examples/x-to-zkevm-migration-app/**"

  # Setup catalog file versions for core packages like typescript/eslint