---
name: "Notify Slack Publish Status"
description: "Notify Slack with the completion status of the publish action"
inputs:
  webhook:
    description: "Slack incoming webhook URL"
    required: true
  message:
    description: "Message to send to Slack"
    required: true
    default: ""
runs:
  using: "node24"
  main: "dist/index.js"
