/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActivityNFT } from './activity-nft';
// May contain unused imports in some cases
// @ts-ignore
import { ActivityToken } from './activity-token';
// May contain unused imports in some cases
// @ts-ignore
import { ContractType } from './contract-type';

/**
 * @type ActivityAsset
 * The contract and asset details for this activity
 * @export
 */
export type ActivityAsset = ActivityNFT | ActivityToken;


