/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TokenContractType } from './token-contract-type';

/**
 * 
 * @export
 * @interface ActivityToken
 */
export interface ActivityToken {
    /**
     * 
     * @type {TokenContractType}
     * @memberof ActivityToken
     */
    'contract_type': TokenContractType;
    /**
     * The contract address
     * @type {string}
     * @memberof ActivityToken
     */
    'contract_address': string;
}

