/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The verification status for a given contract
 * @export
 * @enum {string}
 */

export const AssetVerificationStatus = {
    Pending: 'pending',
    Verified: 'verified',
    Unverified: 'unverified',
    Spam: 'spam',
    Inactive: 'inactive'
} as const;

export type AssetVerificationStatus = typeof AssetVerificationStatus[keyof typeof AssetVerificationStatus];



