/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The chain details
 * @export
 * @interface Chain
 */
export interface Chain {
    /**
     * The id of chain
     * @type {string}
     * @memberof Chain
     */
    'id': string;
    /**
     * The name of chain
     * @type {string}
     * @memberof Chain
     */
    'name': string;
}

