/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DomainWithNumericChainId
 */
export interface DomainWithNumericChainId {
    /**
     * 
     * @type {string}
     * @memberof DomainWithNumericChainId
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainWithNumericChainId
     */
    'version'?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainWithNumericChainId
     */
    'chainId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainWithNumericChainId
     */
    'verifyingContract'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainWithNumericChainId
     */
    'salt'?: string;
}

