/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EIP712MessageDomain } from './eip712-message-domain';
// May contain unused imports in some cases
// @ts-ignore
import { EIP712MessageTypes } from './eip712-message-types';

/**
 * 
 * @export
 * @interface EIP712Message
 */
export interface EIP712Message {
    /**
     * 
     * @type {EIP712MessageTypes}
     * @memberof EIP712Message
     */
    'types': EIP712MessageTypes;
    /**
     * 
     * @type {string}
     * @memberof EIP712Message
     */
    'primaryType': string;
    /**
     * 
     * @type {EIP712MessageDomain}
     * @memberof EIP712Message
     */
    'domain': EIP712MessageDomain;
    /**
     * 
     * @type {object}
     * @memberof EIP712Message
     */
    'message': object;
}

