/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EIP712MessageTypesEIP712DomainInner } from './eip712-message-types-eip712-domain-inner';

/**
 * 
 * @export
 * @interface EIP712MessageTypes
 */
export interface EIP712MessageTypes {
    [key: string]: Array<EIP712MessageTypesEIP712DomainInner>;

    /**
     * 
     * @type {Array<EIP712MessageTypesEIP712DomainInner>}
     * @memberof EIP712MessageTypes
     */
    'EIP712Domain': Array<EIP712MessageTypesEIP712DomainInner>;
}

