/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FailedOrderCancellation
 */
export interface FailedOrderCancellation {
    /**
     * ID of the order which failed to be cancelled
     * @type {string}
     * @memberof FailedOrderCancellation
     */
    'order': string;
    /**
     * Reason code indicating why the order failed to be cancelled
     * @type {string}
     * @memberof FailedOrderCancellation
     */
    'reason_code': FailedOrderCancellationReasonCodeEnum;
}

export const FailedOrderCancellationReasonCodeEnum = {
    Filled: 'FILLED'
} as const;

export type FailedOrderCancellationReasonCodeEnum = typeof FailedOrderCancellationReasonCodeEnum[keyof typeof FailedOrderCancellationReasonCodeEnum];


