/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FulfillmentData200ResponseResult } from './fulfillment-data200-response-result';

/**
 * 
 * @export
 * @interface FulfillmentData200Response
 */
export interface FulfillmentData200Response {
    /**
     * 
     * @type {FulfillmentData200ResponseResult}
     * @memberof FulfillmentData200Response
     */
    'result': FulfillmentData200ResponseResult;
}

