/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Order } from './order';

/**
 * 
 * @export
 * @interface FulfillableOrder
 */
export interface FulfillableOrder {
    /**
     * 
     * @type {Order}
     * @memberof FulfillableOrder
     */
    'order': Order;
    /**
     * Token ID for the ERC721 or ERC1155 token when fulfilling a collection order
     * @type {string}
     * @memberof FulfillableOrder
     */
    'token_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillableOrder
     */
    'extra_data': string;
}

