/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SeaportCreateListingMetadata } from './seaport-create-listing-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportCreateListingMetadataBuy } from './seaport-create-listing-metadata-buy';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportCreateListingMetadataSell } from './seaport-create-listing-metadata-sell';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportFee } from './seaport-fee';
// May contain unused imports in some cases
// @ts-ignore
import { UnknownTypedDataMetadata } from './unknown-typed-data-metadata';

/**
 * @type GetTypedDataMetadataRes
 * @export
 */
export type GetTypedDataMetadataRes = SeaportCreateListingMetadata | UnknownTypedDataMetadata;


