/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ERC20ApproveMetadata } from './erc20-approve-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { ERC20TransferFromMetadata } from './erc20-transfer-from-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { ERC20TransferMetadata } from './erc20-transfer-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721ApproveMetadata } from './erc721-approve-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721SafeTransferFromBatchItem } from './erc721-safe-transfer-from-batch-item';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721SafeTransferFromBatchMetadata } from './erc721-safe-transfer-from-batch-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721TransferFromMetadata } from './erc721-transfer-from-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { NFTSetApprovalForAllMetadata } from './nftset-approval-for-all-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportAdvancedOrder } from './seaport-advanced-order';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportFulfillAvailableAdvancedOrdersMetadata } from './seaport-fulfill-available-advanced-orders-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { UnknownMetadata } from './unknown-metadata';

/**
 * @type GetTransactionMetadataRes
 * @export
 */
export type GetTransactionMetadataRes = ERC20ApproveMetadata | ERC20TransferFromMetadata | ERC20TransferMetadata | ERC721ApproveMetadata | ERC721SafeTransferFromBatchMetadata | ERC721TransferFromMetadata | NFTSetApprovalForAllMetadata | SeaportFulfillAvailableAdvancedOrdersMetadata | UnknownMetadata;


