/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ERC20Item } from './erc20-item';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721Item } from './erc721-item';
// May contain unused imports in some cases
// @ts-ignore
import { NativeItem } from './native-item';

/**
 * @type Item
 * @export
 */
export type Item = { item_type: 'ERC20' } & ERC20Item | { item_type: 'ERC721' } & ERC721Item | { item_type: 'NATIVE' } & NativeItem;


