/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NFTMetadataAttribute } from './nftmetadata-attribute';

/**
 * List of normalized NFT metadata attributes
 * @export
 * @interface NFTMetadataAttributes
 */
export interface NFTMetadataAttributes {
    /**
     * List of NFT Metadata attributes
     * @type {Array<NFTMetadataAttribute>}
     * @memberof NFTMetadataAttributes
     */
    'attributes': Array<NFTMetadataAttribute>;
}

