/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActivityType } from './activity-type';
// May contain unused imports in some cases
// @ts-ignore
import { ERC721Token } from './erc721-token';
// May contain unused imports in some cases
// @ts-ignore
import { NFTSalePaymentToken } from './nftsale-payment-token';

/**
 * The NFT Sale activity details
 * @export
 * @interface NFTSale
 */
export interface NFTSale {
    /**
     * 
     * @type {ActivityType}
     * @memberof NFTSale
     */
    'activity_type': ActivityType;
    /**
     * The id of order
     * @type {string}
     * @memberof NFTSale
     */
    'order_id': string;
    /**
     * The account address of buyer
     * @type {string}
     * @memberof NFTSale
     */
    'buyer_address': string;
    /**
     * The account address of seller
     * @type {string}
     * @memberof NFTSale
     */
    'seller_address': string;
    /**
     * The quantity of tokens sold
     * @type {number}
     * @memberof NFTSale
     */
    'quantity': number;
    /**
     * 
     * @type {ERC721Token}
     * @memberof NFTSale
     */
    'token': ERC721Token;
    /**
     * The amount of payment
     * @type {string}
     * @memberof NFTSale
     */
    'payment_amount': string;
    /**
     * 
     * @type {NFTSalePaymentToken}
     * @memberof NFTSale
     */
    'payment_token': NFTSalePaymentToken;
}

