/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NFTMetadataAttribute } from './nftmetadata-attribute';

/**
 * 
 * @export
 * @interface RefreshableNFTAttributes
 */
export interface RefreshableNFTAttributes {
    /**
     * The name of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'name': string | null;
    /**
     * The description of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'description': string | null;
    /**
     * The image url of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'image': string | null;
    /**
     * The external link of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'external_url': string | null;
    /**
     * The animation url of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'animation_url': string | null;
    /**
     * The youtube link of the NFT
     * @type {string}
     * @memberof RefreshableNFTAttributes
     */
    'youtube_url': string | null;
    /**
     * List of Metadata attributes
     * @type {Array<NFTMetadataAttribute>}
     * @memberof RefreshableNFTAttributes
     */
    'attributes': Array<NFTMetadataAttribute> | null;
}

