/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ImmutableVerificationStatusEnum } from './immutable-verification-status-enum';

/**
 * 
 * @export
 * @interface SeaportERC721CollectionItem
 */
export interface SeaportERC721CollectionItem {
    /**
     * Token type user is offering, which in this case is ERC721Collection
     * @type {string}
     * @memberof SeaportERC721CollectionItem
     */
    'type': SeaportERC721CollectionItemTypeEnum;
    /**
     * Address of ERC721 token
     * @type {string}
     * @memberof SeaportERC721CollectionItem
     */
    'contract_address': string;
    /**
     * The name of the collection
     * @type {string}
     * @memberof SeaportERC721CollectionItem
     */
    'contract_name'?: string | null;
    /**
     * The URL of the collection image
     * @type {string}
     * @memberof SeaportERC721CollectionItem
     */
    'image_url': string;
    /**
     * A string representing the total units of an ERC721 token which the user is buying
     * @type {string}
     * @memberof SeaportERC721CollectionItem
     */
    'amount': string;
    /**
     * 
     * @type {ImmutableVerificationStatusEnum}
     * @memberof SeaportERC721CollectionItem
     */
    'immutable_verification_status': ImmutableVerificationStatusEnum;
}

export const SeaportERC721CollectionItemTypeEnum = {
    Erc721Collection: 'ERC721Collection'
} as const;

export type SeaportERC721CollectionItemTypeEnum = typeof SeaportERC721CollectionItemTypeEnum[keyof typeof SeaportERC721CollectionItemTypeEnum];


