/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SeaportCreateListingMetadataBuy } from './seaport-create-listing-metadata-buy';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportERC721Item } from './seaport-erc721-item';
// May contain unused imports in some cases
// @ts-ignore
import { SeaportFee } from './seaport-fee';

/**
 * 
 * @export
 * @interface SeaportCreateListingMetadata
 */
export interface SeaportCreateListingMetadata {
    /**
     * Typed data type
     * @type {string}
     * @memberof SeaportCreateListingMetadata
     */
    'typed_data_type': SeaportCreateListingMetadataTypedDataTypeEnum;
    /**
     * 
     * @type {SeaportCreateListingMetadataBuy}
     * @memberof SeaportCreateListingMetadata
     */
    'buy': SeaportCreateListingMetadataBuy;
    /**
     * 
     * @type {SeaportERC721Item}
     * @memberof SeaportCreateListingMetadata
     */
    'sell': SeaportERC721Item;
    /**
     * 
     * @type {Array<SeaportFee>}
     * @memberof SeaportCreateListingMetadata
     */
    'fees': Array<SeaportFee>;
}

export const SeaportCreateListingMetadataTypedDataTypeEnum = {
    SeaportCreateListingMetadata: 'SEAPORT_CREATE_LISTING_METADATA'
} as const;

export type SeaportCreateListingMetadataTypedDataTypeEnum = typeof SeaportCreateListingMetadataTypedDataTypeEnum[keyof typeof SeaportCreateListingMetadataTypedDataTypeEnum];


