/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SeaportNativeItem
 */
export interface SeaportNativeItem {
    /**
     * Token type user is offering, which in this case is the native IMX token
     * @type {string}
     * @memberof SeaportNativeItem
     */
    'type': SeaportNativeItemTypeEnum;
    /**
     * A string representing the price at which the user is willing to sell the token
     * @type {string}
     * @memberof SeaportNativeItem
     */
    'amount': string;
    /**
     * The decimal of this item
     * @type {number}
     * @memberof SeaportNativeItem
     */
    'decimals': number;
}

export const SeaportNativeItemTypeEnum = {
    Native: 'NATIVE'
} as const;

export type SeaportNativeItemTypeEnum = typeof SeaportNativeItemTypeEnum[keyof typeof SeaportNativeItemTypeEnum];


