/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Chain } from './chain';
// May contain unused imports in some cases
// @ts-ignore
import { NFTMetadataAttribute } from './nftmetadata-attribute';

/**
 * Stack
 * @export
 * @interface Stack
 */
export interface Stack {
    /**
     * Stack ID
     * @type {string}
     * @memberof Stack
     */
    'stack_id': string;
    /**
     * 
     * @type {Chain}
     * @memberof Stack
     */
    'chain': Chain;
    /**
     * Contract address
     * @type {string}
     * @memberof Stack
     */
    'contract_address': string;
    /**
     * When the metadata was created
     * @type {string}
     * @memberof Stack
     */
    'created_at': string;
    /**
     * When the metadata was last updated
     * @type {string}
     * @memberof Stack
     */
    'updated_at': string;
    /**
     * The name of the NFT
     * @type {string}
     * @memberof Stack
     */
    'name': string | null;
    /**
     * The description of the NFT
     * @type {string}
     * @memberof Stack
     */
    'description': string | null;
    /**
     * The image url of the NFT
     * @type {string}
     * @memberof Stack
     */
    'image': string | null;
    /**
     * The external website link of NFT
     * @type {string}
     * @memberof Stack
     */
    'external_url': string | null;
    /**
     * The animation url of the NFT
     * @type {string}
     * @memberof Stack
     */
    'animation_url': string | null;
    /**
     * The youtube URL of NFT
     * @type {string}
     * @memberof Stack
     */
    'youtube_url': string | null;
    /**
     * List of Metadata attributes
     * @type {Array<NFTMetadataAttribute>}
     * @memberof Stack
     */
    'attributes': Array<NFTMetadataAttribute> | null;
}

