/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Chain } from './chain';
// May contain unused imports in some cases
// @ts-ignore
import { Fee } from './fee';
// May contain unused imports in some cases
// @ts-ignore
import { Item } from './item';
// May contain unused imports in some cases
// @ts-ignore
import { TradeBlockchainMetadata } from './trade-blockchain-metadata';

/**
 * 
 * @export
 * @interface Trade
 */
export interface Trade {
    /**
     * 
     * @type {Array<Item>}
     * @memberof Trade
     */
    'buy': Array<Item>;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    'buyer_address': string;
    /**
     * 
     * @type {Array<Fee>}
     * @memberof Trade
     */
    'buyer_fees': Array<Fee>;
    /**
     * 
     * @type {Chain}
     * @memberof Trade
     */
    'chain': Chain;
    /**
     * 
     * @type {TradeBlockchainMetadata}
     * @memberof Trade
     */
    'blockchain_metadata'?: TradeBlockchainMetadata | null;
    /**
     * Time the Trade is created
     * @type {string}
     * @memberof Trade
     */
    'create_time': string;
    /**
     * Global Trade identifier
     * @type {string}
     * @memberof Trade
     */
    'id': string;
    /**
     * 
     * @type {Array<Item>}
     * @memberof Trade
     */
    'sell': Array<Item>;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    'seller_address': string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    'maker_address': string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    'taker_address': string;
    /**
     * Time the Trade is last updated
     * @type {string}
     * @memberof Trade
     */
    'update_time': string;
}

