/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnknownMetadata
 */
export interface UnknownMetadata {
    /**
     * Transaction type
     * @type {string}
     * @memberof UnknownMetadata
     */
    'transaction_type': UnknownMetadataTransactionTypeEnum;
    /**
     * Indicate if it is a Smart Contract or EOA
     * @type {boolean}
     * @memberof UnknownMetadata
     */
    'is_smart_contract': boolean;
    /**
     * Is Contract Verified
     * @type {boolean}
     * @memberof UnknownMetadata
     */
    'is_contract_verified': boolean;
    /**
     * Smart Contract Name
     * @type {string}
     * @memberof UnknownMetadata
     */
    'contract_name': string;
}

export const UnknownMetadataTransactionTypeEnum = {
    Unknown: 'UNKNOWN'
} as const;

export type UnknownMetadataTransactionTypeEnum = typeof UnknownMetadataTransactionTypeEnum[keyof typeof UnknownMetadataTransactionTypeEnum];


