/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnknownTypedDataMetadata
 */
export interface UnknownTypedDataMetadata {
    /**
     * Unknown typed data type
     * @type {string}
     * @memberof UnknownTypedDataMetadata
     */
    'typed_data_type': UnknownTypedDataMetadataTypedDataTypeEnum;
}

export const UnknownTypedDataMetadataTypedDataTypeEnum = {
    Unknown: 'UNKNOWN'
} as const;

export type UnknownTypedDataMetadataTypedDataTypeEnum = typeof UnknownTypedDataMetadataTypedDataTypeEnum[keyof typeof UnknownTypedDataMetadataTypedDataTypeEnum];


