/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Linked wallet
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * Ethereum address
     * @type {string}
     * @memberof Wallet
     */
    'address': string;
    /**
     * Wallet type
     * @type {string}
     * @memberof Wallet
     */
    'type': string;
    /**
     * Created at
     * @type {string}
     * @memberof Wallet
     */
    'created_at': string;
    /**
     * Created at
     * @type {string}
     * @memberof Wallet
     */
    'updated_at': string;
    /**
     * Name
     * @type {string}
     * @memberof Wallet
     */
    'name'?: string;
    /**
     * Name of client that linked the wallet
     * @type {string}
     * @memberof Wallet
     */
    'clientName': string;
}

