/* tslint:disable */
/* eslint-disable */
/**
 * ItemDefinition API
 * Item Definition API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HttpUpdateItemDefinitionRequest
 */
export interface HttpUpdateItemDefinitionRequest {
    /**
     * 
     * @type {string}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'description'?: string;
    /**
     * Image URL
     * @type {string}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'image'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'item_template_id': string;
    /**
     * 
     * @type {string}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'name': string;
    /**
     * JSON Object of item properties
     * @type {object}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'properties'?: object;
    /**
     * 
     * @type {string}
     * @memberof HttpUpdateItemDefinitionRequest
     */
    'status'?: HttpUpdateItemDefinitionRequestStatusEnum;
}

export const HttpUpdateItemDefinitionRequestStatusEnum = {
    Draft: 'draft',
    Published: 'published'
} as const;

export type HttpUpdateItemDefinitionRequestStatusEnum = typeof HttpUpdateItemDefinitionRequestStatusEnum[keyof typeof HttpUpdateItemDefinitionRequestStatusEnum];


