/* tslint:disable */
/* eslint-disable */
/**
 * ItemDefinition API
 * Item Definition API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HttpCreateItemTemplateRequest
 */
export interface HttpCreateItemTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemTemplateRequest
     */
    'game_id': string;
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemTemplateRequest
     */
    'name': string;
    /**
     * 
     * @type {object}
     * @memberof HttpCreateItemTemplateRequest
     */
    'property_schema': object;
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemTemplateRequest
     */
    'type_id': string;
}

