/* tslint:disable */
/* eslint-disable */
/**
 * ItemDefinition API
 * Item Definition API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HttpCreateItemDefinitionRequest
 */
export interface HttpCreateItemDefinitionRequest {
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'game_id': string;
    /**
     * Image URL
     * @type {string}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'image'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'item_template_id': string;
    /**
     * 
     * @type {string}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'name': string;
    /**
     * JSON Object of item properties
     * @type {object}
     * @memberof HttpCreateItemDefinitionRequest
     */
    'properties'?: object;
}

