/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MintTokenData } from './mint-token-data';

/**
 * @type MintTokenDataOAIGen
 * Token details of this asset
 * @export
 */
export type MintTokenDataOAIGen = MintTokenData;


