/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// @ts-ignore
import { APIError400 } from '../models';
// @ts-ignore
import { APIError401 } from '../models';
// @ts-ignore
import { APIError403 } from '../models';
// @ts-ignore
import { APIError404 } from '../models';
// @ts-ignore
import { APIError500 } from '../models';
// @ts-ignore
import { SignCraftingRequest } from '../models';
// @ts-ignore
import { SignCraftingResult } from '../models';
// @ts-ignore
export type { APIError400 } from '../models';
// @ts-ignore
export type { APIError401 } from '../models';
// @ts-ignore
export type { APIError403 } from '../models';
// @ts-ignore
export type { APIError404 } from '../models';
// @ts-ignore
export type { APIError500 } from '../models';
// @ts-ignore
export type { SignCraftingRequest } from '../models';
// @ts-ignore
export type { SignCraftingResult } from '../models';

/**
 * Request parameters for signCraftingPayload operation in CraftingApi.
 * @export
 * @interface SignCraftingPayloadRequest
 */
export interface SignCraftingPayloadRequestParams {
    /**
     * The name of chain
     * @type {string}
     * @memberof SignCraftingPayload
     */
    readonly chainName: string

    /**
     * The request body
     * @type {SignCraftingRequest}
     * @memberof SignCraftingPayload
     */
    readonly signCraftingRequest: SignCraftingRequest
}


