/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// @ts-ignore
import { APIError400 } from '../models';
// @ts-ignore
import { APIError401 } from '../models';
// @ts-ignore
import { APIError403 } from '../models';
// @ts-ignore
import { APIError404 } from '../models';
// @ts-ignore
import { APIError429 } from '../models';
// @ts-ignore
import { APIError500 } from '../models';
// @ts-ignore
import { CreateMintRequestRequest } from '../models';
// @ts-ignore
import { CreateMintRequestResult } from '../models';
// @ts-ignore
import { GetNFTResult } from '../models';
// @ts-ignore
import { ListMintRequestsResult } from '../models';
// @ts-ignore
import { ListNFTsByOwnerResult } from '../models';
// @ts-ignore
import { ListNFTsResult } from '../models';
// @ts-ignore
import { MintRequestStatus } from '../models';
// @ts-ignore
export { APIError400 } from '../models';
// @ts-ignore
export { APIError401 } from '../models';
// @ts-ignore
export { APIError403 } from '../models';
// @ts-ignore
export { APIError404 } from '../models';
// @ts-ignore
export { APIError429 } from '../models';
// @ts-ignore
export { APIError500 } from '../models';
// @ts-ignore
export { CreateMintRequestRequest } from '../models';
// @ts-ignore
export { CreateMintRequestResult } from '../models';
// @ts-ignore
export { GetNFTResult } from '../models';
// @ts-ignore
export { ListMintRequestsResult } from '../models';
// @ts-ignore
export { ListNFTsByOwnerResult } from '../models';
// @ts-ignore
export { ListNFTsResult } from '../models';
// @ts-ignore
export { MintRequestStatus } from '../models';

/**
 * Request parameters for createMintRequest operation in NftsApi.
 * @export
 * @interface CreateMintRequestRequest
 */
export interface CreateMintRequestRequestParams {
    /**
     * The address of contract
     * @type {string}
     * @memberof CreateMintRequest
     */
    readonly contractAddress: string

    /**
     * The name of chain
     * @type {string}
     * @memberof CreateMintRequest
     */
    readonly chainName: string

    /**
     * Create Mint Request Body
     * @type {CreateMintRequestRequest}
     * @memberof CreateMintRequest
     */
    readonly createMintRequestRequest: CreateMintRequestRequest
}

/**
 * Request parameters for getMintRequest operation in NftsApi.
 * @export
 * @interface GetMintRequestRequest
 */
export interface GetMintRequestRequestParams {
    /**
     * The address of contract
     * @type {string}
     * @memberof GetMintRequest
     */
    readonly contractAddress: string

    /**
     * The name of chain
     * @type {string}
     * @memberof GetMintRequest
     */
    readonly chainName: string

    /**
     * The id of the mint request
     * @type {string}
     * @memberof GetMintRequest
     */
    readonly referenceId: string
}

/**
 * Request parameters for getNFT operation in NftsApi.
 * @export
 * @interface GetNFTRequest
 */
export interface GetNFTRequestParams {
    /**
     * The address of NFT contract
     * @type {string}
     * @memberof GetNFT
     */
    readonly contractAddress: string

    /**
     * An &#x60;uint256&#x60; token id as string
     * @type {string}
     * @memberof GetNFT
     */
    readonly tokenId: string

    /**
     * The name of chain
     * @type {string}
     * @memberof GetNFT
     */
    readonly chainName: string
}

/**
 * Request parameters for listAllNFTs operation in NftsApi.
 * @export
 * @interface ListAllNFTsRequest
 */
export interface ListAllNFTsRequestParams {
    /**
     * The name of chain
     * @type {string}
     * @memberof ListAllNFTs
     */
    readonly chainName: string

    /**
     * Datetime to use as the oldest updated timestamp
     * @type {string}
     * @memberof ListAllNFTs
     */
    readonly fromUpdatedAt?: string

    /**
     * Encoded page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof ListAllNFTs
     */
    readonly pageCursor?: string

    /**
     * Maximum number of items to return
     * @type {number}
     * @memberof ListAllNFTs
     */
    readonly pageSize?: number
}

/**
 * Request parameters for listMintRequests operation in NftsApi.
 * @export
 * @interface ListMintRequestsRequest
 */
export interface ListMintRequestsRequestParams {
    /**
     * The address of contract
     * @type {string}
     * @memberof ListMintRequests
     */
    readonly contractAddress: string

    /**
     * The name of chain
     * @type {string}
     * @memberof ListMintRequests
     */
    readonly chainName: string

    /**
     * Encoded page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof ListMintRequests
     */
    readonly pageCursor?: string

    /**
     * Maximum number of items to return
     * @type {number}
     * @memberof ListMintRequests
     */
    readonly pageSize?: number

    /**
     * The status of the mint request
     * @type {MintRequestStatus}
     * @memberof ListMintRequests
     */
    readonly status?: MintRequestStatus
}

/**
 * Request parameters for listNFTs operation in NftsApi.
 * @export
 * @interface ListNFTsRequest
 */
export interface ListNFTsRequestParams {
    /**
     * Contract address
     * @type {string}
     * @memberof ListNFTs
     */
    readonly contractAddress: string

    /**
     * The name of chain
     * @type {string}
     * @memberof ListNFTs
     */
    readonly chainName: string

    /**
     * List of token IDs to filter by
     * @type {Array<string>}
     * @memberof ListNFTs
     */
    readonly tokenId?: Array<string>

    /**
     * Datetime to use as the oldest updated timestamp
     * @type {string}
     * @memberof ListNFTs
     */
    readonly fromUpdatedAt?: string

    /**
     * Encoded page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof ListNFTs
     */
    readonly pageCursor?: string

    /**
     * Maximum number of items to return
     * @type {number}
     * @memberof ListNFTs
     */
    readonly pageSize?: number
}

/**
 * Request parameters for listNFTsByAccountAddress operation in NftsApi.
 * @export
 * @interface ListNFTsByAccountAddressRequest
 */
export interface ListNFTsByAccountAddressRequestParams {
    /**
     * Account address
     * @type {string}
     * @memberof ListNFTsByAccountAddress
     */
    readonly accountAddress: string

    /**
     * The name of chain
     * @type {string}
     * @memberof ListNFTsByAccountAddress
     */
    readonly chainName: string

    /**
     * The address of contract
     * @type {string}
     * @memberof ListNFTsByAccountAddress
     */
    readonly contractAddress?: string

    /**
     * Encoded page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof ListNFTsByAccountAddress
     */
    readonly pageCursor?: string

    /**
     * Maximum number of items to return
     * @type {number}
     * @memberof ListNFTsByAccountAddress
     */
    readonly pageSize?: number
}


