/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignDataResponse
 */
export interface SignDataResponse {
    /**
     * 
     * @type {string}
     * @memberof SignDataResponse
     */
    'message_hash': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponse
     */
    'signature': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponse
     */
    'r': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponse
     */
    's': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponse
     */
    'v': string;
}

