/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * DemopageApi - axios parameter creator
 * @export
 */
export const DemopageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Demopage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        demoPage: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/demopage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DemopageApi - functional programming interface
 * @export
 */
export const DemopageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DemopageApiAxiosParamCreator(configuration)
    return {
        /**
         * Demopage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async demoPage(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.demoPage(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DemopageApi - factory interface
 * @export
 */
export const DemopageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DemopageApiFp(configuration)
    return {
        /**
         * Demopage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        demoPage(options?: any): AxiosPromise<string> {
            return localVarFp.demoPage(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DemopageApi - object-oriented interface
 * @export
 * @class DemopageApi
 * @extends {BaseAPI}
 */
export class DemopageApi extends BaseAPI {
    /**
     * Demopage
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DemopageApi
     */
    public demoPage(options?: AxiosRequestConfig) {
        return DemopageApiFp(this.configuration).demoPage(options).then((request) => request(this.axios, this.basePath));
    }
}
