/* tslint:disable */
/* eslint-disable */
/**
 * Crafting API
 * Crafting API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CraftCreateCraftOutput
 */
export interface CraftCreateCraftOutput {
    /**
     * 
     * @type {string}
     * @memberof CraftCreateCraftOutput
     */
    'game_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CraftCreateCraftOutput
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CraftCreateCraftOutput
     */
    'recipe_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CraftCreateCraftOutput
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CraftCreateCraftOutput
     */
    'user_id'?: string;
}

