/* tslint:disable */
/* eslint-disable */
/**
 * Crafting API
 * Crafting API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CraftFieldError } from './craft-field-error';

/**
 * 
 * @export
 * @interface CraftValidationErrors
 */
export interface CraftValidationErrors {
    /**
     * 
     * @type {Array<CraftFieldError>}
     * @memberof CraftValidationErrors
     */
    'errors'?: Array<CraftFieldError>;
    /**
     * 
     * @type {string}
     * @memberof CraftValidationErrors
     */
    'message'?: string;
}

