/* tslint:disable */
/* eslint-disable */
/**
 * Inventory API
 * Inventory API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { InventoryBatchRequestItems } from './inventory-batch-request-items';

/**
 * 
 * @export
 * @interface InventoryBatchRequest
 */
export interface InventoryBatchRequest {
    /**
     * 
     * @type {InventoryBatchRequestItems}
     * @memberof InventoryBatchRequest
     */
    'items'?: InventoryBatchRequestItems;
}

