/* tslint:disable */
/* eslint-disable */
/**
 * Inventory API
 * Inventory API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InventoryCreateItemRequest
 */
export interface InventoryCreateItemRequest {
    /**
     * 
     * @type {string}
     * @memberof InventoryCreateItemRequest
     */
    'item_definition_id': string;
    /**
     * Location of the item. Can be one of the following values: * offchain - Off chain, only in the inventory system. * starkex - On the StarkEx Network. * zkevm - On the ZK EVM Network.
     * @type {string}
     * @memberof InventoryCreateItemRequest
     */
    'location': InventoryCreateItemRequestLocationEnum;
    /**
     * JSON Object of item properties e.g. {\"Level\": 2, \"Rarity\": \"Common\"}
     * @type {object}
     * @memberof InventoryCreateItemRequest
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof InventoryCreateItemRequest
     */
    'owner': string;
}

export const InventoryCreateItemRequestLocationEnum = {
    Offchain: 'offchain',
    Zkevm: 'zkevm',
    Starkex: 'starkex'
} as const;

export type InventoryCreateItemRequestLocationEnum = typeof InventoryCreateItemRequestLocationEnum[keyof typeof InventoryCreateItemRequestLocationEnum];


