/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActivityAsset } from './activity-asset';
// May contain unused imports in some cases
// @ts-ignore
import { Burn } from './burn';
// May contain unused imports in some cases
// @ts-ignore
import { Deposit } from './deposit';
// May contain unused imports in some cases
// @ts-ignore
import { Mint } from './mint';
// May contain unused imports in some cases
// @ts-ignore
import { NFTSale } from './nftsale';
// May contain unused imports in some cases
// @ts-ignore
import { SalePayment } from './sale-payment';
// May contain unused imports in some cases
// @ts-ignore
import { Transfer } from './transfer';
// May contain unused imports in some cases
// @ts-ignore
import { Withdrawal } from './withdrawal';

/**
 * @type ActivityDetails
 * The activity details
 * @export
 */
export type ActivityDetails = Burn | Deposit | Mint | NFTSale | Transfer | Withdrawal;


