/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionMetadata
 */
export interface CollectionMetadata {
    /**
     * The name of the collection
     * @type {string}
     * @memberof CollectionMetadata
     */
    'name': string | null;
    /**
     * The symbol of contract
     * @type {string}
     * @memberof CollectionMetadata
     */
    'symbol': string | null;
    /**
     * The description of collection
     * @type {string}
     * @memberof CollectionMetadata
     */
    'description': string | null;
    /**
     * The url of the collection image
     * @type {string}
     * @memberof CollectionMetadata
     */
    'image': string | null;
    /**
     * The url of external link
     * @type {string}
     * @memberof CollectionMetadata
     */
    'external_link': string | null;
    /**
     * The uri for the metadata of the collection
     * @type {string}
     * @memberof CollectionMetadata
     */
    'contract_uri': string | null;
    /**
     * The metadata uri for nft
     * @type {string}
     * @memberof CollectionMetadata
     */
    'base_uri': string | null;
}

