/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ERC20Item
 */
export interface ERC20Item {
    /**
     * Token type user is offering, which in this case is ERC20
     * @type {string}
     * @memberof ERC20Item
     */
    'type': ERC20ItemTypeEnum;
    /**
     * Address of ERC20 token
     * @type {string}
     * @memberof ERC20Item
     */
    'contract_address': string;
    /**
     * A string representing the price at which the user is willing to sell the token. This value is provided in the smallest unit of the token (e.g., wei for Ethereum).
     * @type {string}
     * @memberof ERC20Item
     */
    'amount': string;
}

/**
    * @export
    * @enum {string}
    */
export enum ERC20ItemTypeEnum {
    Erc20 = 'ERC20'
}


