/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExpiredOrderStatus
 */
export interface ExpiredOrderStatus {
    /**
     * A terminal order status indicating that an order cannot be fulfilled due to expiry.
     * @type {string}
     * @memberof ExpiredOrderStatus
     */
    'name': ExpiredOrderStatusNameEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ExpiredOrderStatusNameEnum {
    Expired = 'EXPIRED'
}


