/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilledOrderStatus
 */
export interface FilledOrderStatus {
    /**
     * A terminal order status indicating that an order has been fulfilled.
     * @type {string}
     * @memberof FilledOrderStatus
     */
    'name': FilledOrderStatusNameEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FilledOrderStatusNameEnum {
    Filled = 'FILLED'
}


