/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NFTMetadataRequest } from './nftmetadata-request';

/**
 * 
 * @export
 * @interface MintAsset
 */
export interface MintAsset {
    /**
     * The id of this asset in the system that originates the mint request
     * @type {string}
     * @memberof MintAsset
     */
    'reference_id': string;
    /**
     * The address of the receiver
     * @type {string}
     * @memberof MintAsset
     */
    'owner_address': string;
    /**
     * An optional `uint256` token id as string. Required for ERC1155 collections.
     * @type {string}
     * @memberof MintAsset
     */
    'token_id'?: string | null;
    /**
     * Optional mount of tokens to mint. Required for ERC1155 collections. ERC712 collections can omit this field or set it to 1
     * @type {string}
     * @memberof MintAsset
     */
    'amount'?: string | null;
    /**
     * 
     * @type {NFTMetadataRequest}
     * @memberof MintAsset
     */
    'metadata'?: NFTMetadataRequest;
}

