/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// @ts-ignore
import { APIError400 } from '../models';
// @ts-ignore
import { APIError401 } from '../models';
// @ts-ignore
import { APIError404 } from '../models';
// @ts-ignore
import { APIError429 } from '../models';
// @ts-ignore
import { APIError500 } from '../models';
// @ts-ignore
import { APIError501 } from '../models';
// @ts-ignore
import { CancelOrdersRequestBody } from '../models';
// @ts-ignore
import { CancelOrdersResult } from '../models';
// @ts-ignore
import { CreateListingRequestBody } from '../models';
// @ts-ignore
import { FulfillmentData200Response } from '../models';
// @ts-ignore
import { FulfillmentDataRequest } from '../models';
// @ts-ignore
import { ListListingsResult } from '../models';
// @ts-ignore
import { ListTradeResult } from '../models';
// @ts-ignore
import { ListingResult } from '../models';
// @ts-ignore
import { OrderStatus } from '../models';
// @ts-ignore
import { TradeResult } from '../models';
// @ts-ignore
export { APIError400 } from '../models';
// @ts-ignore
export { APIError401 } from '../models';
// @ts-ignore
export { APIError404 } from '../models';
// @ts-ignore
export { APIError429 } from '../models';
// @ts-ignore
export { APIError500 } from '../models';
// @ts-ignore
export { APIError501 } from '../models';
// @ts-ignore
export { CancelOrdersRequestBody } from '../models';
// @ts-ignore
export { CancelOrdersResult } from '../models';
// @ts-ignore
export { CreateListingRequestBody } from '../models';
// @ts-ignore
export { FulfillmentData200Response } from '../models';
// @ts-ignore
export { FulfillmentDataRequest } from '../models';
// @ts-ignore
export { ListListingsResult } from '../models';
// @ts-ignore
export { ListTradeResult } from '../models';
// @ts-ignore
export { ListingResult } from '../models';
// @ts-ignore
export { OrderStatus } from '../models';
// @ts-ignore
export { TradeResult } from '../models';

/**
 * Request parameters for cancelOrders operation in OrdersApi.
 * @export
 * @interface OrdersApiCancelOrdersRequest
 */
export interface OrdersApiCancelOrdersRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiCancelOrders
     */
    readonly chainName: string

    /**
     * 
     * @type {CancelOrdersRequestBody}
     * @memberof OrdersApiCancelOrders
     */
    readonly cancelOrdersRequestBody: CancelOrdersRequestBody
}

/**
 * Request parameters for createListing operation in OrdersApi.
 * @export
 * @interface OrdersApiCreateListingRequest
 */
export interface OrdersApiCreateListingRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiCreateListing
     */
    readonly chainName: string

    /**
     * 
     * @type {CreateListingRequestBody}
     * @memberof OrdersApiCreateListing
     */
    readonly createListingRequestBody: CreateListingRequestBody
}

/**
 * Request parameters for fulfillmentData operation in OrdersApi.
 * @export
 * @interface OrdersApiFulfillmentDataRequest
 */
export interface OrdersApiFulfillmentDataRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiFulfillmentData
     */
    readonly chainName: string

    /**
     * 
     * @type {Array<FulfillmentDataRequest>}
     * @memberof OrdersApiFulfillmentData
     */
    readonly fulfillmentDataRequest: Array<FulfillmentDataRequest>
}

/**
 * Request parameters for getListing operation in OrdersApi.
 * @export
 * @interface OrdersApiGetListingRequest
 */
export interface OrdersApiGetListingRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiGetListing
     */
    readonly chainName: string

    /**
     * Global Order identifier
     * @type {string}
     * @memberof OrdersApiGetListing
     */
    readonly listingId: string
}

/**
 * Request parameters for getTrade operation in OrdersApi.
 * @export
 * @interface OrdersApiGetTradeRequest
 */
export interface OrdersApiGetTradeRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiGetTrade
     */
    readonly chainName: string

    /**
     * Global Trade identifier
     * @type {string}
     * @memberof OrdersApiGetTrade
     */
    readonly tradeId: string
}

/**
 * Request parameters for listListings operation in OrdersApi.
 * @export
 * @interface OrdersApiListListingsRequest
 */
export interface OrdersApiListListingsRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiListListings
     */
    readonly chainName: string

    /**
     * Order status to filter by
     * @type {OrderStatus}
     * @memberof OrdersApiListListings
     */
    readonly status?: OrderStatus

    /**
     * Sell item contract address to filter by
     * @type {string}
     * @memberof OrdersApiListListings
     */
    readonly sellItemContractAddress?: string

    /**
     * Buy item contract address to filter by
     * @type {string}
     * @memberof OrdersApiListListings
     */
    readonly buyItemContractAddress?: string

    /**
     * Sell item token identifier to filter by
     * @type {string}
     * @memberof OrdersApiListListings
     */
    readonly sellItemTokenId?: string

    /**
     * Maximum number of orders to return per page
     * @type {number}
     * @memberof OrdersApiListListings
     */
    readonly pageSize?: number

    /**
     * Order field to sort by
     * @type {'created_at' | 'updated_at' | 'buy_item_amount'}
     * @memberof OrdersApiListListings
     */
    readonly sortBy?: SortByEnum

    /**
     * Ascending or descending direction for sort
     * @type {'asc' | 'desc'}
     * @memberof OrdersApiListListings
     */
    readonly sortDirection?: SortDirectionEnum

    /**
     * Page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof OrdersApiListListings
     */
    readonly pageCursor?: string
}

/**
 * Request parameters for listTrades operation in OrdersApi.
 * @export
 * @interface OrdersApiListTradesRequest
 */
export interface OrdersApiListTradesRequest {
    /**
     * 
     * @type {string}
     * @memberof OrdersApiListTrades
     */
    readonly chainName: string

    /**
     * 
     * @type {string}
     * @memberof OrdersApiListTrades
     */
    readonly accountAddress?: string

    /**
     * Maximum number of trades to return per page
     * @type {number}
     * @memberof OrdersApiListTrades
     */
    readonly pageSize?: number

    /**
     * Trade field to sort by
     * @type {'indexed_at'}
     * @memberof OrdersApiListTrades
     */
    readonly sortBy?: SortByEnum

    /**
     * Ascending or descending direction for sort
     * @type {'asc' | 'desc'}
     * @memberof OrdersApiListTrades
     */
    readonly sortDirection?: SortDirectionEnum

    /**
     * Page cursor to retrieve previous or next page. Use the value returned in the response.
     * @type {string}
     * @memberof OrdersApiListTrades
     */
    readonly pageCursor?: string
}


/**
 * @export
 */
export const ListListingsSortByEnum = {
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    BuyItemAmount: 'buy_item_amount'
} as const;
export type ListListingsSortByEnum = typeof ListListingsSortByEnum[keyof typeof ListListingsSortByEnum];
/**
 * @export
 */
export const ListListingsSortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListListingsSortDirectionEnum = typeof ListListingsSortDirectionEnum[keyof typeof ListListingsSortDirectionEnum];
/**
 * @export
 */
export const ListTradesSortByEnum = {
    IndexedAt: 'indexed_at'
} as const;
export type ListTradesSortByEnum = typeof ListTradesSortByEnum[keyof typeof ListTradesSortByEnum];
/**
 * @export
 */
export const ListTradesSortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListTradesSortDirectionEnum = typeof ListTradesSortDirectionEnum[keyof typeof ListTradesSortDirectionEnum];
