/* tslint:disable */
/* eslint-disable */
/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// @ts-ignore
import { APIError400 } from '../models';
// @ts-ignore
import { APIError401 } from '../models';
// @ts-ignore
import { APIError403 } from '../models';
// @ts-ignore
import { APIError429 } from '../models';
// @ts-ignore
import { APIError500 } from '../models';
// @ts-ignore
import { BasicAPIError } from '../models';
// @ts-ignore
import { CreateCounterfactualAddressRequest } from '../models';
// @ts-ignore
import { CreateCounterfactualAddressRequestDeprecated } from '../models';
// @ts-ignore
import { CreateCounterfactualAddressRes } from '../models';
// @ts-ignore
import { CreateCounterfactualAddressResDeprecated } from '../models';
// @ts-ignore
import { GetLinkedAddressesRes } from '../models';
// @ts-ignore
import { GetLinkedAddressesResDeprecated } from '../models';
// @ts-ignore
export { APIError400 } from '../models';
// @ts-ignore
export { APIError401 } from '../models';
// @ts-ignore
export { APIError403 } from '../models';
// @ts-ignore
export { APIError429 } from '../models';
// @ts-ignore
export { APIError500 } from '../models';
// @ts-ignore
export { BasicAPIError } from '../models';
// @ts-ignore
export { CreateCounterfactualAddressRequestDeprecated } from '../models';
// @ts-ignore
export { CreateCounterfactualAddressRes } from '../models';
// @ts-ignore
export { CreateCounterfactualAddressResDeprecated } from '../models';
// @ts-ignore
export { GetLinkedAddressesRes } from '../models';
// @ts-ignore
export { GetLinkedAddressesResDeprecated } from '../models';

/**
 * Request parameters for createCounterfactualAddress operation in PassportApi.
 * @export
 * @interface CreateCounterfactualAddressRequest
 */
export interface CreateCounterfactualAddressRequest {
    /**
     *
     * @type {string}
     * @memberof CreateCounterfactualAddress
     */
    readonly chainName: string

    /**
     *
     * @type {CreateCounterfactualAddressRequest}
     * @memberof CreateCounterfactualAddress
     */
    readonly createCounterfactualAddressRequest: CreateCounterfactualAddressRequest
}

/**
 * Request parameters for createCounterfactualAddressDeprecated operation in PassportApi.
 * @export
 * @interface CreateCounterfactualAddressDeprecatedRequest
 */
export interface CreateCounterfactualAddressDeprecatedRequest {
    /**
     *
     * @type {CreateCounterfactualAddressRequestDeprecated}
     * @memberof CreateCounterfactualAddressDeprecated
     */
    readonly createCounterfactualAddressRequestDeprecated: CreateCounterfactualAddressRequestDeprecated
}

/**
 * Request parameters for getLinkedAddresses operation in PassportApi.
 * @export
 * @interface GetLinkedAddressesRequest
 */
export interface GetLinkedAddressesRequest {
    /**
     * The user\&#39;s userId
     * @type {string}
     * @memberof GetLinkedAddresses
     */
    readonly userId: string

    /**
     *
     * @type {string}
     * @memberof GetLinkedAddresses
     */
    readonly chainName: string
}

/**
 * Request parameters for getLinkedAddressesDeprecated operation in PassportApi.
 * @export
 * @interface GetLinkedAddressesDeprecatedRequest
 */
export interface GetLinkedAddressesDeprecatedRequest {
    /**
     * The user\&#39;s userId
     * @type {string}
     * @memberof GetLinkedAddressesDeprecated
     */
    readonly userId: string
}


