/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImmutableERC721Base } from "./ImmutableERC721Base";
export * as factories from "./factories";
export { ImmutableERC721Base__factory } from "./factories/ImmutableERC721Base__factory";
