/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type CancelOrdersRequestBody = {
  /**
   * Address of the user initiating the cancel request
   */
  account_address: string;
  /**
   * List of order ids proposed for cancellation
   */
  orders: Array<string>;
  /**
   * Signature generated by the user for the specific cancellation request
   */
  signature: string;
};

