/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AssetCollectionItem } from './AssetCollectionItem';
import type { ERC20Item } from './ERC20Item';
import type { Fee } from './Fee';
import type { MetadataFieldFilter } from './MetadataFieldFilter';
import type { ProtocolData } from './ProtocolData';

export type CreateMetadataBidRequestBody = {
  account_address: string;
  order_hash: string;
  /**
   * Buy item for metadata bid should either be ERC721 or ERC1155 collection item
   */
  buy: Array<AssetCollectionItem>;
  /**
   * Buy fees should only include maker marketplace fees and should be no more than two entries as more entires will incur more gas. It is best practice to have this as few as possible.
   */
  fees: Array<Fee>;
  /**
   * Time after which the Order is considered expired
   */
  end_at: string;
  protocol_data: ProtocolData;
  /**
   * A random value added to the create Order request
   */
  salt: string;
  /**
   * Sell item for metadata bid should be an ERC20 item
   */
  sell: Array<ERC20Item>;
  /**
   * Digital signature generated by the user for the specific Order
   */
  signature: string;
  /**
   * Time after which Order is considered active
   */
  start_at: string;
  /**
   * The metadata_id (stack_id) that NFTs must have to fulfil this bid.
   * Mutually exclusive with `metadata_criteria`; exactly one must be set.
   */
  metadata_id?: string;
  /**
   * Field-level metadata filters that NFTs must satisfy to fulfil this bid.
   * Mutually exclusive with `metadata_id`; exactly one must be set.
   */
  metadata_criteria?: Array<MetadataFieldFilter>;
};
