/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BuyItem } from './BuyItem';
import type { Fee } from './Fee';
import type { OrderStatus } from './OrderStatus';
import type { ProtocolData } from './ProtocolData';
import type { SellItem } from './SellItem';

export type Order = {
  account_address: string;
  buy: Array<BuyItem>;
  buy_fees: Array<Fee>;
  /**
   * Chain identifier using the CAIP-2 blockchain id spec
   */
  chain_id: string;
  /**
   * Time the Order is created
   */
  create_time: string;
  /**
   * Time after which the Order is considered expired
   */
  end_time: string;
  /**
   * Global Order identifier
   */
  id: string;
  protocol_data: ProtocolData;
  /**
   * A random value added to the create Order request
   */
  salt: string;
  sell: Array<SellItem>;
  /**
   * Digital signature generated by the user for the specific Order
   */
  signature: string;
  /**
   * Time after which Order is considered active
   */
  start_time: string;
  status: OrderStatus;
  /**
   * Time the Order is last updated
   */
  update_time: string;
};

