/* tslint:disable */
/* eslint-disable */
/**
 * Recipe API
 * Recipe API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DomainOutput
 */
export interface DomainOutput {
    /**
     * 
     * @type {object}
     * @memberof DomainOutput
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainOutput
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainOutput
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainOutput
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainOutput
     */
    'ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainOutput
     */
    'type'?: string;
}

