/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { WalletResponseModel } from '../models';
/**
 * WalletApi - axios parameter creator
 * @export
 */
export const WalletApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Wallet
         * @param {string} xMagicChain 
         * @param {string} [xMagicAPIKey] 
         * @param {string} [xMagicSecretKey] 
         * @param {string} [xOIDCProviderID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWalletV1WalletPost: async (xMagicChain: string, xMagicAPIKey?: string, xMagicSecretKey?: string, xOIDCProviderID?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xMagicChain' is not null or undefined
            assertParamExists('createWalletV1WalletPost', 'xMagicChain', xMagicChain)
            const localVarPath = `/v1/wallet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xMagicChain != null) {
                localVarHeaderParameter['X-Magic-Chain'] = String(xMagicChain);
            }

            if (xMagicAPIKey != null) {
                localVarHeaderParameter['X-Magic-API-Key'] = String(xMagicAPIKey);
            }

            if (xMagicSecretKey != null) {
                localVarHeaderParameter['X-Magic-Secret-Key'] = String(xMagicSecretKey);
            }

            if (xOIDCProviderID != null) {
                localVarHeaderParameter['X-OIDC-Provider-ID'] = String(xOIDCProviderID);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WalletApi - functional programming interface
 * @export
 */
export const WalletApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WalletApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Wallet
         * @param {string} xMagicChain 
         * @param {string} [xMagicAPIKey] 
         * @param {string} [xMagicSecretKey] 
         * @param {string} [xOIDCProviderID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWalletV1WalletPost(xMagicChain: string, xMagicAPIKey?: string, xMagicSecretKey?: string, xOIDCProviderID?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponseModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWalletV1WalletPost(xMagicChain, xMagicAPIKey, xMagicSecretKey, xOIDCProviderID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * WalletApi - factory interface
 * @export
 */
export const WalletApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WalletApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Wallet
         * @param {WalletApiCreateWalletV1WalletPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWalletV1WalletPost(requestParameters: WalletApiCreateWalletV1WalletPostRequest, options?: AxiosRequestConfig): AxiosPromise<WalletResponseModel> {
            return localVarFp.createWalletV1WalletPost(requestParameters.xMagicChain, requestParameters.xMagicAPIKey, requestParameters.xMagicSecretKey, requestParameters.xOIDCProviderID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createWalletV1WalletPost operation in WalletApi.
 * @export
 * @interface WalletApiCreateWalletV1WalletPostRequest
 */
export interface WalletApiCreateWalletV1WalletPostRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletApiCreateWalletV1WalletPost
     */
    readonly xMagicChain: string

    /**
     * 
     * @type {string}
     * @memberof WalletApiCreateWalletV1WalletPost
     */
    readonly xMagicAPIKey?: string

    /**
     * 
     * @type {string}
     * @memberof WalletApiCreateWalletV1WalletPost
     */
    readonly xMagicSecretKey?: string

    /**
     * 
     * @type {string}
     * @memberof WalletApiCreateWalletV1WalletPost
     */
    readonly xOIDCProviderID?: string
}

/**
 * WalletApi - object-oriented interface
 * @export
 * @class WalletApi
 * @extends {BaseAPI}
 */
export class WalletApi extends BaseAPI {
    /**
     * 
     * @summary Create Wallet
     * @param {WalletApiCreateWalletV1WalletPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletApi
     */
    public createWalletV1WalletPost(requestParameters: WalletApiCreateWalletV1WalletPostRequest, options?: AxiosRequestConfig) {
        return WalletApiFp(this.configuration).createWalletV1WalletPost(requestParameters.xMagicChain, requestParameters.xMagicAPIKey, requestParameters.xMagicSecretKey, requestParameters.xOIDCProviderID, options).then((request) => request(this.axios, this.basePath));
    }
}

