name: "Playwright setup"
description: "Install the browsers and dependencies for Playwright to run"

runs:
  using: "composite"
  steps:
    - name: Playwright versions in sync check
      shell: bash
      run: |
        versions=$(pnpm ls -r --json --depth 0 @playwright/test | jq --raw-output '.[] | select(.devDependencies["@playwright/test"]) | .devDependencies["@playwright/test"].version')
        unique_versions=$(echo "$versions" | sort | uniq)
        if [ $(echo "$unique_versions" | wc -l) -ne 1 ]; then
          echo "Playwright versions are not in sync:"
          echo "$unique_versions"
          exit 1
        else
          echo "All Playwright versions are in sync."
          echo "PLAYWRIGHT_VERSION=$unique_versions" >> $GITHUB_ENV
        fi
        
    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright with dependencies
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: pnpm dlx playwright@${{ env.PLAYWRIGHT_VERSION }} install --with-deps

    - name: Install Playwright dependencies
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      run: pnpm dlx playwright@${{ env.PLAYWRIGHT_VERSION }} install-deps