name: "Playwright setup"
description: "Install the browsers and dependencies for Playwright to run"

runs:
  using: "composite"
  steps:
    - name: Get Playwright version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('playwright/package.json').version)")" >> $GITHUB_ENV

    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright with dependencies
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: yarn dlx playwright install --with-deps

    - name: Install Playwright dependencies
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      run: yarn dlx playwright install-deps