name: Build and test all example apps

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-4-cores
    env:
      NODE_OPTIONS: --max-old-space-size=14366
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/
          cache: "yarn"

      - name: Find all projects
        id: find-projects
        run: |
          find ./examples/passport -name 'node_modules' -prune -o -name 'package.json' -exec dirname {} \; > project-dirs.txt
          
      - name: Install, Build, and Test
        run: |
          while IFS= read -r dir; do
            echo "Processing $dir"
            (cd "$dir" && yarn install && yarn build)
            if jq -e '.scripts.test' "$dir/package.json" > /dev/null; then
              (cd "$dir" && yarn test)
            else
              echo "No test script found in $dir/package.json, skipping tests."
            fi
          done < project-dirs.txt