name: Build and test all example apps

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-4-cores
    env:
      NODE_OPTIONS: --max-old-space-size=14366
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/pr-setup
        
      - name: Build Projects
        run: yarn build:examples
        
      - name: Run Tests
        run: yarn test:examples