name: 'Dependency Review'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Dependency Review
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: critical

          # Address https://github.com/actions/dependency-review-action/issues/456
          base-ref: ${{ github.event.pull_request.base.sha || github.event.repository.default_branch }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
