name: Deploy Economy Playground Storybook

on:
  push:
    paths:
      - 'packages/economy/playground/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ secrets.CHROMATIC_PROJECT_TOKEN }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
        
      - name: Build Checkout SDK
        run: yarn workspace @imtbl/checkout-sdk build && yarn workspace @imtbl/checkout-widgets build

      - name: Build Economy SDK
        run: yarn workspace @imtbl/economy build

      - name: Build Storybook Economy Playground
        run: yarn workspace @imtbl/economy-playground build

      - name: Build Package Economy Playground
        run: yarn workspace @imtbl/economy-playground build:package

      - name: Navigate to Economy Playground
        run: cd packages/economy/playground

      - name: Publish Economy Playground to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} -d "../../packages/economy/playground/storybook-static" --exit-zero-on-changes
