name: Deploy Economy Playground Storybook

on:
  push:
    paths:
      - 'packages/economy/playground/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: export NODE_OPTIONS=--max-old-space-size=6144 && yarn build
        
      - name: Build Checkout SDK
        run: yarn workspace @imtbl/checkout-sdk build && yarn workspace @imtbl/checkout-widgets build

      - name: Build Economy SDK
        run: yarn workspace @imtbl/economy build

      - name: Build Storybook Economy Playground
        run: yarn workspace @imtbl/economy-playground build

      - name: Build Package Economy Playground
        run: yarn workspace @imtbl/economy-playground build:package
        
      - name: Setup checkout-widget-lib dependencies
        run: yarn workspace @imtbl/economy-playground setup

      - name: Navigate to Economy Playground
        run: cd packages/economy/playground

      - name: Publish Economy Playground to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} -d ${{ github.workspace }}/packages/economy/playground/storybook-static --exit-zero-on-changes
