name: Functional Tests
on:
  push:
    branches: [ main, DX-2485/gherkin-tests ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install root dependencies
      run: npm install -g yarn && yarn install --immutable

    - name: Build SDK
      run: yarn build

    - name: Install functional tests dependencies
      run: cd func-tests && yarn install --no-immutable

    - name: Run tests
      env:
        NETWORK: sepolia
        TOKEN_ADDRESS: '0x2Fa06C6672dDCc066Ab04631192738799231dE4a'
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        PRIVATE_KEY1: ${{ secrets.PRIVATE_KEY1 }}
        STARK_PRIVATE_KEY1: ${{ secrets.STARK_PRIVATE_KEY1 }}
        PRIVATE_KEY_BANKER: ${{ secrets.PRIVATE_KEY_BANKER }}
        STARK_PRIVATE_KEY_BANKER: ${{ secrets.STARK_PRIVATE_KEY_BANKER }}
        TAGS: 'not @skip'
      run: cd func-tests && yarn test
