name: Passport SDK Sample App Deployment

on:
  push:
    paths:
      - "packages/passport/**"
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: passport-sdk-sample-app-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Passport SDK Sample App
    runs-on: ubuntu-latest
    environment: cdn-deploy
    permissions:
      id-token: write # Required for GitHub OIDC to assume the AWS role
      contents: read
    env:
      AWS_REGION: us-east-2
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.TS_IMMUTABLE_SDK_NX_TOKEN }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # pin@v6.2.2
        with:
          role-to-assume: ${{ secrets.AWS_IMMUTABLE_PROD_ADMIN_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: setup
        uses: ./.github/actions/setup
        with:
          enable-cache: "false"

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Initialize and install current @latest sdk versions on npm
        shell: bash
        run: pnpm --filter @imtbl/sdk... exec sh -c "jq --arg version \"$(npm view @imtbl/metrics versions --json | jq -r '.[-1]')\" '.version = \$version' package.json > package.tmp.json && mv package.tmp.json package.json" && pnpm i --ignore-scripts

      - name: Build Static Passport sample app
        shell: bash
        run: pnpm nx run @imtbl/passport-sdk-sample-app:build --skip-nx-cache

      - name: Upload to S3
        shell: bash
        run: |
          aws s3 sync ./packages/passport/sdk-sample-app/out s3://imx-passport-frontend-prod/sdk-sample-app

      - name: Clear the cloudfront cache
        env:
          CF_DISTRIBUTION_ID: ${{ secrets.CF_PASSPORT_PROD_DISTRIBUTION_ID }}
        shell: bash
        run: |
          aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/*"
