name: Checkout PR

on:
  pull_request:
    branches:
      - main
    paths: 
      - 'packages/checkout/**'

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.TS_IMMUTABLE_SDK_NX_TOKEN }}

jobs: 
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      checkout: ${{ steps.filter.outputs.checkout }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            checkout:
              - 'packages/checkout/**'

  build-lint-test-example-widgets-with-sdk:
    needs: changes
    name: Build, Lint & Test Example Widgets with latest SDK
    runs-on: ubuntu-latest-8-cores
    env:
      NODE_OPTIONS: --max-old-space-size=14366
    steps:
      - name: Check PR affects checkout package
        if: needs.changes.outputs.checkout != 'true'
        run: |
          echo "::notice title=Skipping tests::No changes detected in packages/checkout. Exiting job."
          exit 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: setup
        uses: ./.github/actions/setup

      - name: Get current SDK version string
        uses: actions/github-script@v7.0.1
        with: 
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log("Current SDK version: ", latestRelease.tag_name);
            return latestRelease.tag_name;
          result-encoding: string
        id: version

      - name: Install SDK at current version
        run: yarn workspace @examples/sdk-load-widgets-with-nextjs add @imtbl/sdk@${{ steps.version.outputs.result }}

      - name: Build next app
        run: yarn workspace @examples/sdk-load-widgets-with-nextjs build

      - name: Build everything
        run: yarn build

      - name: Build local widgets bundle
        run: yarn workspace @imtbl/checkout-widgets build:examplewidgets

      - name: Lint examples
        run: yarn workspace @examples/sdk-load-widgets-with-nextjs lint

      - name: Setup playwright
        uses: ./.github/actions/setup-playwright

      - name: Test Widget example
        run: yarn workspace @examples/sdk-load-widgets-with-nextjs test:latest