name: Title Validation

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - edited

permissions:
  pull-requests: read

jobs:
  title-validation:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@40166f00814508ec3201fc8595b393d451c8cd80
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true